import { NextResponse } from "next/server";
import JSZip from "jszip";
import { supabase } from "@/lib/supabase";
import type { SiteConfig } from "@/types/site-config";
import { FONT_PAIRINGS } from "@/lib/themes/fonts";

export async function POST(request: Request) {
  try {
    const { siteId } = await request.json();

    if (!siteId) {
      return NextResponse.json({ error: "siteId is required" }, { status: 400 });
    }

    let config: SiteConfig;

    if (siteId === "test") {
      const { TEST_CONFIG } = await import("@/lib/test-config");
      config = TEST_CONFIG;
    } else {
      const { data, error } = await supabase.from("sites").select("config").eq("id", siteId).single();
      if (error || !data) {
        return NextResponse.json({ error: "Site not found" }, { status: 404 });
      }
      config = data.config as SiteConfig;
    }

    const zip = new JSZip();
    const fontPair = FONT_PAIRINGS[config.theme.fontPairing];

    // package.json
    zip.file("package.json", JSON.stringify({
      name: config.company.name.toLowerCase().replace(/[^a-z0-9]/g, "-"),
      version: "1.0.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "^16.0.0",
        react: "^19.0.0",
        "react-dom": "^19.0.0",
        "lucide-react": "^1.0.0",
      },
      devDependencies: {
        typescript: "^5.0.0",
        "@types/node": "^20.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
      },
    }, null, 2));

    // next.config.ts
    zip.file("next.config.ts", `import type { NextConfig } from "next";\nconst config: NextConfig = {};\nexport default config;\n`);

    // tsconfig.json
    zip.file("tsconfig.json", JSON.stringify({
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    }, null, 2));

    // .gitignore
    zip.file(".gitignore", "node_modules\n.next\n.env*\n");

    // Site config as a TS file
    zip.file("src/lib/site-config.ts", `import type { SiteConfig } from "../types/site-config";\n\nexport const siteConfig: SiteConfig = ${JSON.stringify(config, null, 2)};\n`);

    // Simplified types file
    zip.file("src/types/site-config.ts", "// Types are embedded in the config. See src/lib/site-config.ts\nexport type SiteConfig = any;\nexport type PageConfig = any;\nexport type SectionConfig = any;\nexport type CompanyInfo = any;\nexport type ThemeConfig = any;\nexport type NavbarConfig = any;\nexport type FooterConfig = any;\nexport type IntegrationsConfig = any;\n");

    // Layout with fonts
    const googleFontsUrl = `https://fonts.googleapis.com/css2?family=${fontPair.googleHeading}&family=${fontPair.googleBody}&display=swap`;
    zip.file("src/app/layout.tsx", `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${config.seo.defaultTitle}",
  description: "${config.seo.defaultDescription}",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="${googleFontsUrl}" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
`);

    // Globals CSS with baked theme values
    const c = config.theme.colors;
    zip.file("src/app/globals.css", `/* Generated by freelance-ez */
:root {
  --t-bg-primary: ${c.bgPrimary};
  --t-bg-secondary: ${c.bgSecondary};
  --t-bg-tertiary: ${c.bgTertiary};
  --t-bg-card: ${c.bgCard};
  --t-primary: ${c.primary};
  --t-primary-light: ${c.primaryLight};
  --t-primary-dark: ${c.primaryDark};
  --t-text-primary: ${c.textPrimary};
  --t-text-secondary: ${c.textSecondary};
  --t-text-muted: ${c.textMuted};
  --t-text-inverse: ${c.textInverse};
  --t-border: ${c.border};
  --t-border-hover: ${c.borderHover};
  --t-success: ${c.success};
  --t-font-heading: '${fontPair.heading}', ${fontPair.headingFallback};
  --t-font-body: '${fontPair.body}', ${fontPair.bodyFallback};
}

* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: var(--t-font-body);
  background: var(--t-bg-primary);
  color: var(--t-text-primary);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}
`);

    // README
    zip.file("README.md", `# ${config.company.name}

Generated by [freelance-ez](https://freelance-ez.vercel.app).

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Deploy

Push to GitHub and import on [Vercel](https://vercel.com).
`);

    // Home page placeholder
    zip.file("src/app/page.tsx", `export default function Home() {
  return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>
      <h1>Welcome to ${config.company.name}</h1>
      <p>This is your exported site. Connect your template components to bring it to life.</p>
    </div>
  );
}
`);

    const content = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(content, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${config.company.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}.zip"`,
      },
    });
  } catch (err) {
    console.error("Export error:", err);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
