import type { ThemePreset, ThemeColors } from "@/types/site-config";

export interface ThemePresetDefinition {
  name: ThemePreset;
  label: string;
  mode: "dark" | "light";
  description: string;
  colors: ThemeColors;
}

export const THEME_PRESETS: Record<ThemePreset, ThemePresetDefinition> = {
  // ==================== DARK THEMES ====================

  "dark-copper": {
    name: "dark-copper",
    label: "Dark Copper",
    mode: "dark",
    description: "Premium luxury — warm copper on deep black",
    colors: {
      bgPrimary: "#0a0a0a",
      bgSecondary: "#111111",
      bgTertiary: "#1a1a1a",
      bgCard: "#141414",
      primary: "#B87333",
      primaryLight: "#DA9A65",
      primaryDark: "#945720",
      textPrimary: "#f0f0f0",
      textSecondary: "#a0a0a0",
      textMuted: "#888888",
      textInverse: "#0a0a0a",
      border: "#222222",
      borderHover: "#333333",
      success: "#22c55e",
    },
  },

  "dark-emerald": {
    name: "dark-emerald",
    label: "Dark Emerald",
    mode: "dark",
    description: "Deep charcoal with green accent — nature, growth, health",
    colors: {
      bgPrimary: "#0d1117",
      bgSecondary: "#141a22",
      bgTertiary: "#1c242e",
      bgCard: "#161d27",
      primary: "#10B981",
      primaryLight: "#34D399",
      primaryDark: "#059669",
      textPrimary: "#e6edf3",
      textSecondary: "#8b949e",
      textMuted: "#7d8590",
      textInverse: "#0d1117",
      border: "#21262d",
      borderHover: "#30363d",
      success: "#22c55e",
    },
  },

  "dark-sapphire": {
    name: "dark-sapphire",
    label: "Dark Sapphire",
    mode: "dark",
    description: "Navy-black with blue accent — tech, trust, corporate",
    colors: {
      bgPrimary: "#0a0f1e",
      bgSecondary: "#111827",
      bgTertiary: "#1a2237",
      bgCard: "#131b2e",
      primary: "#3B82F6",
      primaryLight: "#60A5FA",
      primaryDark: "#2563EB",
      textPrimary: "#e2e8f0",
      textSecondary: "#94a3b8",
      textMuted: "#8494a7",
      textInverse: "#0a0f1e",
      border: "#1e293b",
      borderHover: "#334155",
      success: "#22c55e",
    },
  },

  "dark-rose": {
    name: "dark-rose",
    label: "Dark Rose",
    mode: "dark",
    description: "Charcoal with warm pink — beauty, fashion, creative",
    colors: {
      bgPrimary: "#111111",
      bgSecondary: "#1a1a1a",
      bgTertiary: "#222222",
      bgCard: "#1c1c1c",
      primary: "#F43F5E",
      primaryLight: "#FB7185",
      primaryDark: "#E11D48",
      textPrimary: "#f5f5f5",
      textSecondary: "#a3a3a3",
      textMuted: "#8a8a8a",
      textInverse: "#111111",
      border: "#262626",
      borderHover: "#383838",
      success: "#22c55e",
    },
  },

  "dark-amber": {
    name: "dark-amber",
    label: "Dark Amber",
    mode: "dark",
    description: "Deep brown-black with gold — finance, luxury, premium",
    colors: {
      bgPrimary: "#0f0d09",
      bgSecondary: "#1a1610",
      bgTertiary: "#231e16",
      bgCard: "#1c1812",
      primary: "#F59E0B",
      primaryLight: "#FBBF24",
      primaryDark: "#D97706",
      textPrimary: "#f5f0e8",
      textSecondary: "#a89f8f",
      textMuted: "#8a8278",
      textInverse: "#0f0d09",
      border: "#2a2418",
      borderHover: "#3d3528",
      success: "#22c55e",
    },
  },

  "dark-violet": {
    name: "dark-violet",
    label: "Dark Violet",
    mode: "dark",
    description: "Dark purple-black with lavender — creative, gaming, tech",
    colors: {
      bgPrimary: "#0e0a1a",
      bgSecondary: "#161024",
      bgTertiary: "#1e162e",
      bgCard: "#181228",
      primary: "#8B5CF6",
      primaryLight: "#A78BFA",
      primaryDark: "#7C3AED",
      textPrimary: "#ede9fe",
      textSecondary: "#a5a0c0",
      textMuted: "#8a85a8",
      textInverse: "#0e0a1a",
      border: "#221b35",
      borderHover: "#332a4a",
      success: "#22c55e",
    },
  },

  // ==================== LIGHT THEMES ====================

  "light-sage": {
    name: "light-sage",
    label: "Light Sage",
    mode: "light",
    description: "Off-white with sage green — organic, calm, wellness",
    colors: {
      bgPrimary: "#FAFAF8",
      bgSecondary: "#F3F3EF",
      bgTertiary: "#EAEAE4",
      bgCard: "#FFFFFF",
      primary: "#6B8F71",
      primaryLight: "#8AB090",
      primaryDark: "#4F7355",
      textPrimary: "#1a1a1a",
      textSecondary: "#555555",
      textMuted: "#888888",
      textInverse: "#ffffff",
      border: "#ddddd8",
      borderHover: "#cccccc",
      success: "#16a34a",
    },
  },

  "light-ocean": {
    name: "light-ocean",
    label: "Light Ocean",
    mode: "light",
    description: "Cool white with ocean blue — professional, SaaS, B2B",
    colors: {
      bgPrimary: "#F8FAFC",
      bgSecondary: "#F1F5F9",
      bgTertiary: "#E2E8F0",
      bgCard: "#FFFFFF",
      primary: "#0369A1",
      primaryLight: "#0284C7",
      primaryDark: "#075985",
      textPrimary: "#0F172A",
      textSecondary: "#475569",
      textMuted: "#94a3b8",
      textInverse: "#ffffff",
      border: "#CBD5E1",
      borderHover: "#94A3B8",
      success: "#16a34a",
    },
  },

  "light-terracotta": {
    name: "light-terracotta",
    label: "Light Terracotta",
    mode: "light",
    description: "Warm cream with terracotta — artisan, food, hospitality",
    colors: {
      bgPrimary: "#FDF8F4",
      bgSecondary: "#F5EDE6",
      bgTertiary: "#EDE2D8",
      bgCard: "#FFFFFF",
      primary: "#C2724F",
      primaryLight: "#D4916F",
      primaryDark: "#A35A3A",
      textPrimary: "#2C1810",
      textSecondary: "#5A4438",
      textMuted: "#8A7568",
      textInverse: "#ffffff",
      border: "#E0D4CA",
      borderHover: "#C8B8A8",
      success: "#16a34a",
    },
  },

  "light-slate": {
    name: "light-slate",
    label: "Light Slate",
    mode: "light",
    description: "Clean white with slate blue — minimal, modern, agency",
    colors: {
      bgPrimary: "#FFFFFF",
      bgSecondary: "#F8F9FA",
      bgTertiary: "#F1F3F5",
      bgCard: "#FFFFFF",
      primary: "#475569",
      primaryLight: "#64748B",
      primaryDark: "#334155",
      textPrimary: "#111111",
      textSecondary: "#555555",
      textMuted: "#999999",
      textInverse: "#ffffff",
      border: "#E5E7EB",
      borderHover: "#D1D5DB",
      success: "#16a34a",
    },
  },

  "light-forest": {
    name: "light-forest",
    label: "Light Forest",
    mode: "light",
    description: "Warm white with deep green — eco, outdoor, consulting",
    colors: {
      bgPrimary: "#FEFCF3",
      bgSecondary: "#F7F4EA",
      bgTertiary: "#EEEAD8",
      bgCard: "#FFFFFF",
      primary: "#15803D",
      primaryLight: "#22C55E",
      primaryDark: "#166534",
      textPrimary: "#14190F",
      textSecondary: "#4A5240",
      textMuted: "#7A8270",
      textInverse: "#ffffff",
      border: "#D8D5C8",
      borderHover: "#C0BEB0",
      success: "#16a34a",
    },
  },

  "light-coral": {
    name: "light-coral",
    label: "Light Coral",
    mode: "light",
    description: "Soft blush with coral — lifestyle, fitness, women-focused",
    colors: {
      bgPrimary: "#FFF5F5",
      bgSecondary: "#FEE2E2",
      bgTertiary: "#FECACA",
      bgCard: "#FFFFFF",
      primary: "#EF4444",
      primaryLight: "#F87171",
      primaryDark: "#DC2626",
      textPrimary: "#1F1111",
      textSecondary: "#5A3F3F",
      textMuted: "#8A7070",
      textInverse: "#ffffff",
      border: "#E8D0D0",
      borderHover: "#D4B0B0",
      success: "#16a34a",
    },
  },
};

export const DARK_PRESETS = Object.values(THEME_PRESETS).filter((t) => t.mode === "dark");
export const LIGHT_PRESETS = Object.values(THEME_PRESETS).filter((t) => t.mode === "light");
